# Generated by Django 4.1.7 on 2023-03-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_updating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen1',
            new_name='BloodGroup1',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen2',
            new_name='BloodGroup2',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen3',
            new_name='BloodGroup3',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen4',
            new_name='BloodGroup4',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen5',
            new_name='BloodGroup5',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen6',
            new_name='BloodGroup6',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen7',
            new_name='BloodGroup7',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygen8',
            new_name='BloodGroup8',
        ),
    ]
