# Generated by Django 4.1.7 on 2023-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_oxygen1_updating_bloodgroup1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup1',
            new_name='bloodgroup1',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup2',
            new_name='bloodgroup2',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup3',
            new_name='bloodgroup3',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup4',
            new_name='bloodgroup4',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup5',
            new_name='bloodgroup5',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup6',
            new_name='bloodgroup6',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup7',
            new_name='bloodgroup7',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='BloodGroup8',
            new_name='bloodgroup8',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygencylinder',
            new_name='oxygencylinder',
        ),
        migrations.RenameField(
            model_name='updating',
            old_name='Oxygenvolume',
            new_name='oxygenvolume',
        ),
    ]
