# Generated by Django 4.1.7 on 2023-03-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_bloodgroup1_updating_bloodgroup1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 8, 47, 49, 639843)),
        ),
        migrations.AddField(
            model_name='updating',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 8, 47, 49, 639843)),
        ),
    ]
