# Generated by Django 4.1.7 on 2023-03-16 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_signup_date_updating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 8, 48, 43, 791955)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='ambulance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='bloodgroup8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 8, 48, 43, 791955)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='ebed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='nbed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='oxygencylinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updating',
            name='oxygenvolume',
            field=models.IntegerField(default=0),
        ),
    ]
