# Generated by Django 4.1.7 on 2023-03-17 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_signup_date_alter_updating_ambulance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 22, 1, 57, 699005)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 22, 1, 57, 699005)),
        ),
    ]
