# Generated by Django 4.1.7 on 2023-03-20 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_signup_date_alter_updating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='updating',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 7, 32, 356092)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 7, 32, 356092)),
        ),
    ]
