# Generated by Django 4.1.7 on 2023-03-20 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_updating_image_alter_signup_date_alter_updating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='updating',
            name='address_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 21, 12, 59, 348851)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 21, 12, 59, 348851)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
