# Generated by Django 4.1.7 on 2023-03-20 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_updating_address_url_alter_signup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 23, 54, 484174)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 23, 54, 485267)),
        ),
        migrations.AlterField(
            model_name='updating',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
    ]
